cod_level: cod-enhanced
data_update_frequency: 30
dataset_source: Multiple sources aggregated by UN OCHA Field Information Services (FIS)
license_id: cc-by-igo
maintainer: maxmalynowsky
methodology: Other
owner_org: hdx
package_creator: HDX Data Systems Team
private: False
subnational: "1"
