services:
  hdx-scraper-cod-ab-global:
    build: .
    env_file: .env
    volumes:
      - ~/.hdx_configuration.yaml:/root/.hdx_configuration.yaml
      - ~/.useragents.yaml:/root/.useragents.yaml
      - ./saved_data:/srv/saved_data
